config/routes.rb
Agradece::Application.routes.draw do
  devise_for :usuarios, :controllers => {:omniauth_callbacks => "usuarios/omniauth_callbacks"}
  
  resources :entries

  resources :usuarios

	match '/' => "display#index"

  root :to => "display#index"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :usuario
  attr_accessible :date, :usuario_id, :goal, :give, :grateful_one, :grateful_two, :grateful_three, :grateful_four, :grateful_five, :grateful_six, :grateful_seven, :grateful_eight, :grateful_nine, :grateful_ten, :thanks, :happy, :evaluation, :improvement, :happier, :still_pending, :greeting
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	has_many :entries
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

	def self.find_for_twitter_oauth(auth_hash)
		usuario = Usuario.find_by_twitter_id auth_hash["uid"]
		if not usuario
			usuario = Usuario.new
			usuario.twitter_id = auth_hash["uid"]
			usuario.name = auth_hash["info"]["name"]
			usuario.email = auth_hash["info"]["nickname"]
			usuario.save!
		end
		return usuario		
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/display_controller.rb
class DisplayController < ApplicationController

	before_filter :authenticate_usuario!, :except => [:index]

	def index	
		@usuario = Usuario.find_by_twitter_id(session["devise.uid"])
	end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_filter :authenticate_usuario!

  def index
    @entries = Usuario.find_by_twitter_id(session["devise.uid"]).entries.sort{|a,b| b[:created_at] <=> a[:created_at]}
  end

  def show
		valida_entry(params[:id], session["devise.uid"])
  end

  def new
    @entry = Entry.new
		@entry.usuario_id = Usuario.find_by_twitter_id(session["devise.uid"]).id
  end

  def create
    @entry = Entry.new(params[:entry])
		@entry.usuario_id = Usuario.find_by_twitter_id(session["devise.uid"]).id
    if @entry.save
      redirect_to @entry, :notice => "Successfully created entry."
    else
      render :action => 'new'
    end
  end

  def edit
		valida_entry(params[:id], session["devise.uid"])
  end

  def update
		valida_entry(params[:id], session["devise.uid"])
    if @entry.update_attributes(params[:entry])
      redirect_to @entry, :notice  => "Successfully updated entry."
    else
      render :action => 'edit'
    end
  end

  def destroy
		valida_entry(params[:id], session["devise.uid"])
    @entry.destroy
    redirect_to entries_url, :notice => "Successfully destroyed entry."
  end

	def valida_entry entry_id, usuario_id
		entry = Entry.find(entry_id)
		if entry.usuario_id == Usuario.find_by_twitter_id(usuario_id).id
			@entry = entry
		else
			redirect_to entries_url, :notice => "The entry is from another user."
		end
	end
end

app/controllers/usuarios/omniauth_callbacks_controller.rb
class Usuarios::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def twitter
		@usuario = Usuario.find_for_twitter_oauth(auth_hash)
		sign_in @usuario
		session["devise.uid"] = auth_hash["uid"]
		redirect_to entries_url
	end

	def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_filter :authenticate_usuario!

  def index
		valida_usuario
    @usuarios = Usuario.all
  end

  def show
		valida_usuario
    @usuario = Usuario.find(params[:id])
  end

  def new
		valida_usuario
    @usuario = Usuario.new
  end

  def create
		valida_usuario
    @usuario = Usuario.new(params[:usuario])
    if @usuario.save
      redirect_to @usuario, :notice => "Successfully created usuario."
    else
      render :action => 'new'
    end
  end

  def edit
		valida_usuario
    @usuario = Usuario.find(params[:id])
  end

  def update
		valida_usuario
    @usuario = Usuario.find(params[:id])
    if @usuario.update_attributes(params[:usuario])
      redirect_to @usuario, :notice  => "Successfully updated usuario."
    else
      render :action => 'edit'
    end
  end

  def destroy
		valida_usuario
    @usuario = Usuario.find(params[:id])
    @usuario.destroy
    redirect_to usuarios_url, :notice => "Successfully destroyed usuario."
  end

	def valida_usuario
		usuario = Usuario.find_by_twitter_id(session["devise.uid"])
		if not usuario.email == "tonklis"
			redirect_to entries_url, :notice => "Invalid user."
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/display/index.html.erb
<% title "Daily gratitude process" %>
<p><strong>Sign up or sign in through</strong></p>

<a href="usuarios/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>Twitter</a>
<div class="clear"></div>

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.date_select :date %>
  </p>
<div>
	<h2> Day </h2>
  <p>
    <%= f.label :goal, "What is my goal for today?" %><br />
    <%= f.text_area :goal, :maxlength => 130, :class => :inputtext %>
  </p>
  <p>
    <%= f.label :give, "What am I willing to give to others around me?" %><br />
    <%= f.text_area :give %>
  </p>
	<p> 10 things that I am grateful for: </p>
  <p>
    <%= f.label :grateful_one, "1." %>
    <%= f.text_field :grateful_one, :maxlength => 130 %>
  </p>
  <p>
    <%= f.label :grateful_two, "2." %>
    <%= f.text_field :grateful_two, :maxlength => 130 %>
  </p>
  <p>
    <%= f.label :grateful_three, "3." %>
    <%= f.text_field :grateful_three, :maxlength => 130 %>
  </p>
  <p>
    <%= f.label :grateful_four, "4." %>
    <%= f.text_field :grateful_four, :maxlength => 130 %>
  </p>
  <p>
    <%= f.label :grateful_five, "5." %>
    <%= f.text_field :grateful_five, :maxlength => 130 %>
  </p>
  <p>
    <%= f.label :grateful_six, "6." %>
    <%= f.text_field :grateful_six, :maxlength => 130 %>
  </p>
  <p>
    <%= f.label :grateful_seven, "7." %>
    <%= f.text_field :grateful_seven, :maxlength => 130 %>
  </p>
  <p>
    <%= f.label :grateful_eight, "8." %>
    <%= f.text_field :grateful_eight, :maxlength => 130 %>
  </p>
  <p>
    <%= f.label :grateful_nine, "9." %>
    <%= f.text_field :grateful_nine, :maxlength => 130 %>
  </p>
  <p>
    <%= f.label :grateful_ten, "10." %>
    <%= f.text_field :grateful_ten, :maxlength => 130, :class => :tenthinput %>
  </p>
  <p>
    <%= f.label :thanks, "Who do I thank for something I have today? Why?" %><br />
    <%= f.text_area :thanks, :class => :inputtext %>
  </p>
  <p>
    <%= f.label :happy, "Why am I happy?" %><br />
    <%= f.text_field :happy, :class => :inputtext %>
  </p>
</div>
<div style="float: right; margin-top: -790px;">
	<h2>Night</h2>
  <p>
    <%= f.label :evaluation, "How well did I do it trying to reach my goal?" %><br />
    <%= f.text_field :evaluation, :class => :inputtext %>
  </p>
  <p>
    <%= f.label :improvement, "What did I learn that added value to my day?" %><br />
    <%= f.text_field :improvement, :class => :inputtext %>
  </p>
  <p>
    <%= f.label :happier, "If I could be happier, why would it be?" %><br />
    <%= f.text_field :happier, :class => :inputtext %>
  </p>
  <p>
    <%= f.label :still_pending, "Which pending activities do I have?" %><br />
    <%= f.text_field :still_pending, :class => :inputtext  %>
  </p>
  <p>
    <%= f.label :greeting, "Who should I greet? (birthdays, anniversaries, special events)" %><br />
    <%= f.text_field :greeting, :class => :inputtext  %>
  </p>
  <%= f.submit :class => :inputbutton %>
<% end %>

app/views/entries/edit.html.erb
<% title "Edit Entry" %>

<%= render 'form' %>

  <%= link_to "Show", @entry %> |
  <%= link_to "Back to List", entries_path %>
</div>

app/views/entries/index.html.erb
<% title "Entries" %>

<table>
  <tr>
    <th>Date</th>
    <th>Goal</th>
  </tr>
  <% for entry in @entries %>
    <tr>
      <td><%= entry.date %></td>
      <td><%= text_area_tag entry.id, entry.goal, :disabled => true, :class => :muestra, :style => "resize: none;" %></td>
      <td><%= link_to "Show", entry %></td>
      <td><%= link_to "Edit", edit_entry_path(entry) %></td>
      <td><%= link_to "Destroy", entry, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Entry", new_entry_path %></p>

app/views/entries/new.html.erb
<% title "New Entry" %>

<%= render 'form' %>

<%= link_to "Back to List", entries_path %>
</div>

app/views/entries/show.html.erb
<% title "Entry" %>

<p>
  <strong>Date:</strong>
  <%= @entry.date %>
</p>
<div>
	<div>
	<h2> Day </h2>
	<p>
		<%= label_tag :goal, "What is your goal for today?" %><br />
  	<%= text_area_tag :goal, @entry.goal, :disabled => true, :maxlength => 130, :class => :inputtext, :style => "resize: none;" %>
	</p>
	<p>
    <%= label_tag :give, "What are you willing to give to others around you?" %><br />
    <%= text_area_tag :give, @entry.give, :disabled => true, :style => "resize: none;" %>
  </p>
	<p> 10 things that you are grateful for: </p>
  <p>
    <%= label_tag :grateful_one, "1." %>
    <%= text_field_tag :grateful_one, @entry.grateful_one, :disabled => true, :maxlength => 130 %>
  </p>
  <p>
    <%= label_tag :grateful_two, "2." %>
    <%= text_field_tag :grateful_two, @entry.grateful_two, :disabled => true, :maxlength => 130 %>
  </p>
  <p>
    <%= label_tag :grateful_three, "3." %>
    <%= text_field_tag :grateful_three, @entry.grateful_three, :disabled => true, :maxlength => 130 %>
  </p>
  <p>
    <%= label_tag :grateful_four, "4." %>
    <%= text_field_tag :grateful_four, @entry.grateful_four, :disabled => true, :maxlength => 130 %>
  </p>
  <p>
    <%= label_tag :grateful_one, "5." %>
    <%= text_field_tag :grateful_five, @entry.grateful_five, :disabled => true, :maxlength => 130 %>
  </p>
  <p>
    <%= label_tag :grateful_six, "6." %>
    <%= text_field_tag :grateful_six, @entry.grateful_six, :disabled => true, :maxlength => 130 %>
  </p>
  <p>
    <%= label_tag :grateful_seven, "7." %>
    <%= text_field_tag :grateful_seven, @entry.grateful_seven, :disabled => true, :maxlength => 130 %>
  </p>
  <p>
    <%= label_tag :grateful_eight, "8." %>
    <%= text_field_tag :grateful_eight, @entry.grateful_eight, :disabled => true, :maxlength => 130 %>
  </p>
  <p>
    <%= label_tag :grateful_nine, "9." %>
    <%= text_field_tag :grateful_one, @entry.grateful_nine, :disabled => true, :maxlength => 130 %>
  </p>
  <p>
    <%= label_tag :grateful_ten, "10." %>
    <%= text_field_tag :grateful_ten, @entry.grateful_ten, :disabled => true, :maxlength => 130, :class => :tenthinput %>
  </p>
	<p>
    <%= label_tag :thanks, "Who do you thank for something you have today? Why?" %><br />
    <%= text_area_tag :thanks, @entry.thanks, :disabled => true, :class => :inputtext, :style => "resize: none;" %>
  </p>
  <p>
    <%= label_tag :happy, "Why are you happy?" %><br />
    <%= text_field_tag :happy, @entry.happy, :disabled => true, :class => :inputtext %>
  </p>
	</div>
	<div style="float: right; margin-top: -790px;">
<h2> Night </h2>
	<p>
    <%= label_tag :evaluation, "How well did I do it trying to reach my goal?" %><br />
    <%= text_field_tag :evaluation, @entry.evaluation, :disabled => true, :class => :inputtext %>
  </p>
  <p>
    <%= label_tag :improvement, "What did I learn that added value to my day?" %><br />
    <%= text_field_tag :improvement, @entry.improvement, :disabled => true, :class => :inputtext %>
  </p>
  <p>
    <%= label_tag :happier, "If I could be happier, why would it be?" %><br />
    <%= text_field_tag :happier, @entry.happier, :disabled => true, :class => :inputtext %>
  </p>
  <p>
    <%= label_tag :still_pending, "Which pending activities do I have?" %><br />
    <%= text_field_tag :still_pending, @entry.still_pending, :disabled => true, :class => :inputtext  %>
  </p>
  <p>
    <%= label_tag :greeting, "Who should I greet? (birthdays, anniversaries, special events)" %><br />
    <%= text_field_tag :greeting, @entry.greeting, :disabled => true, :class => :inputtext  %>
  </p>
<p>
  <%= link_to "Edit", edit_entry_path(@entry) %> |
  <%= link_to "Destroy", @entry, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to List", entries_path %>
</p>
	<div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28907534-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>		
  </head>
  <body>
    <div id="container">
			<div id="user_nav" style="float: right;">
  		<% if usuario_signed_in? %>
    		Signed in as @<%= current_usuario.email %>. Not you?
    		<%= link_to "Sign out", destroy_usuario_session_path, :method => :delete %>
  		<% end %>
			</div>
      <% flash.each do |name, msg| %>
				<br/>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/usuarios/_form.html.erb
<%= form_for @usuario do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/usuarios/edit.html.erb
<% title "Edit Usuario" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @usuario %> |
  <%= link_to "View All", usuarios_path %>
</p>

app/views/usuarios/index.html.erb
<% title "Usuarios" %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>
  <% for usuario in @usuarios %>
    <tr>
      <td><%= usuario.name %></td>
      <td><%= usuario.email %></td>
      <td><%= link_to "Show", usuario %></td>
      <td><%= link_to "Edit", edit_usuario_path(usuario) %></td>
      <td><%= link_to "Destroy", usuario, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Usuario", new_usuario_path %></p>

app/views/usuarios/new.html.erb
<% title "New Usuario" %>

<%= render 'form' %>

<p><%= link_to "Back to List", usuarios_path %></p>

app/views/usuarios/show.html.erb
<% title "Usuario" %>

<p>
  <strong>Name:</strong>
  <%= @usuario.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <%= link_to "Edit", edit_usuario_path(@usuario) %> |
  <%= link_to "Destroy", @usuario, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", usuarios_path %>
</p>